In [6]:
import numpy as np;
a=np.array([1,2,4])
print(type(a))
print(a.shape)
print(a.ndim)
print(a)


<class 'numpy.ndarray'>
(3,)
1
[1 2 4]


In [7]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.ndim)
print(b)


(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [9]:
a=np.zeros((5,5))
print(a)
b=np.ones((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
a=np.full((3,4),69)
print(a)
print(a[1,2],a[2,3])

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]
69 69


In [12]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
a=np.random.random((2,3))
print(a)

[[0.59811672 0.71447897 0.14619533]
 [0.92280701 0.59332381 0.69109342]]


In [22]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,0]]])
b=a[:3,1:3]
print(b)

[[[4 5 6 7]
  [7 8 9 0]]]


In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:3, 1:3]
print(b)



[[ 2  3]
 [ 6  7]
 [10 11]]


In [29]:
a = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]]])
b = a[:1,:1]
print(b)



[[[1 2 3 4]]]
